[package]
name = "kaitai"
version = "0.1.0"
authors = ["Kai Michaelis <kai.michaelis@9elements.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
serde_yaml = "0.8"
serde = { version = "1.0", features = ["derive"] }
charsets = "0.2"
